[#17] Question Mapper 제거
team-saviors/saview-backend pull request #19
Opened 2024-03-19 05:47 UTC by klkim1913

## 작업 요약
- QuestionMapper를 팩토리 메서드 패턴으로 구현하여 변경
- DTO안에다가 모든 메서드 정의
- 기타 자잘한 부분

## 기타 논의하고 싶은 내용
- Mapper부분 + 일부만 수정했습니다. Question 관련 나머지 리팩토링 마저 진행할 예정입니다.
- 리스트 데이터 반환할때 래퍼클래스가 또 필요할지..?

close #17

2024-03-20 14:33 UTC, yeonkkk requested changes
@klkim1913 
경륜님! 이번에도 잘 해주셨군요 ㅎㅎ
질문과 제 생각 조금 남겨보았어요!
천천히 확인하고 답변주세요!
고생하셨습니다 ㅎㅎ

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/dto/Views.java
> +public class Views {
왜 이 Dto는 Views 로 네이밍 하셨나요? 이유가 궁금합니다!

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +@NoArgsConstructor(access = PROTECTED)
static 임포트 하시는 기준이 있나요? 
`@GeneratedValue(strategy = GenerationType.IDENTITY)` 는 안하셨길래 특별한 기준이 있으신지 궁금하네요

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +        this.profile = userPutRequest.getProfile();
파라미터로 nickname과 profile 을 받다가 왜 dto로 변경하셨나요?
그냥 변경 사항만 보기에 메서드 재사용성 자체는 조금 떨어질 수 있을 것 같아서요.

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/user/dto/response/UserAnswersResponse.java
> +import static lombok.AccessLevel.PROTECTED;
사용되지 않는 import 같아요 !

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/service/QuestionService.java
> +            PageRequest.of(page, size, Sort.by(sort).descending()));
👍👍👍

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/entity/Question.java
> +    public Question(String mainCategory, String subCategory, String content, User user) {
builder 를 사용할 거라면 생성자는 private 으로 닫아줘도 좋을 것 같아요!
사용하는 사람이 어떤 것을 사용해야할지 헷갈릴 것 같네요.

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/entity/Question.java
> +    }
updateQuestion으로 메서드명을 할 거라면, 파라미터를 dto로 안받고 content, mainCategory, subCategory 로 받으면 어떤가요? 메서드를 사용하는 입장에서 어떤 값이 업데이트되는지 불분명하게 느껴질 것 같아서요!
아니면 메서드명에 변경되는 필드를 추가하던지, 빌더 패턴을 사용해도 좋을 것 같네요.
경륜님은 어떻게 생각하시나요?

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +    public static List<QuestionListResponse> fromList(List<Question> questionList) {
복수형을 나타내고 싶으면 `fromQuestions()` 같은 메서드명은 어떠신가요?
이름에 List같은 자료형이 들어간다면, 파라미터 타입이 변경됐을 때 같이 변경 될 것 같아요! (예: List -> set 으로 파라미터 타입이 바뀌는 경우)

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +            return list;
if 문에서 null일 경우 빈 리스트를 리턴하고 있기 때문에, else 예약어는 사용하지 않아도 좋을 것 같아요!

관련해서 읽어보면 좋은 글 : https://hudi.blog/thoughtworks-anthology-object-calisthenics/

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +@Builder(access = PRIVATE)
👍👍👍

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +    private LocalDateTime modifiedAt;
클래스 레벨에서 `@FieldDefaults(level = PRIVATE)` 붙여주셨는데 왜 필드에도 붙여주신건가요?!

2024-03-20 14:33 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionDetailResponse.java
> +    private MultiResponseDto<AnswerResponseDto> answers;
> 클래스 레벨에서 `@FieldDefaults(level = PRIVATE)` 붙여주셨는데 왜 필드에도 붙여주신건가요?!

동일한 부분

2024-03-21 04:48 UTC, klkim1913 commented on src/main/java/server/question/dto/Views.java
> +public class Views {
만들어둔 목적이 기억이 안나서 일단 놔뒀는데 다시 보니까 알았네요 ㅎㅎ

2024-03-21 04:51 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
> +@NoArgsConstructor(access = PROTECTED)
못봤네요. 추가 완 ㅎ

2024-03-21 04:55 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
> +        this.profile = userPutRequest.getProfile();
요부분은 처음에 파라미터로 받았는데 인자가 많을수록 Userservice의 이부분에서
```java
public void updateUser(String email, UserPutRequest userPutRequest) {
        User user = userRepository.findByEmail(email);
        user.updateNicknameAndProfile(a,b,c);
    }
```
생성자 대신 빌더 쓰는 이유중 하나와 마찬가지로 파라미터 순서 실수가 영향이 더 크겠다는 생각이 들더라구요.
그리고 저 작업을 필요로하는 로직이 생기면 같은 DTO를 사용할 확률이 높아보이기도 했습니다.

2024-03-21 04:59 UTC, klkim1913 commented on src/main/java/server/user/dto/response/UserAnswersResponse.java
> +import static lombok.AccessLevel.PROTECTED;
이거 IDE에서 잡아주는줄 알았는데 안잡아주는군요..ㄷ

2024-03-21 05:06 UTC, klkim1913 commented on src/main/java/server/question/entity/Question.java
> +    public Question(String mainCategory, String subCategory, String content, User user) {
생각지도 못했네요 감사합니다 :)

2024-03-21 05:11 UTC, klkim1913 commented on src/main/java/server/question/entity/Question.java
> +    }
위와같은 이유였습니다. 이부분은 다음에 얘기해보면 좋을거같네요. 말하신대로 어떤 데이터가 수정되는지 알아야될거같다는 생각도 드네요.

2024-03-21 05:14 UTC, klkim1913 commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +    public static List<QuestionListResponse> fromList(List<Question> questionList) {
일단 저도 이거 이름이 꽤 고민됐네요 ㅋㅋ. 
from도 fromQuestion 안붙이듯이 List가 타입보단 범용적인 의미로 쓰이긴 했는데 성연님 말씀처럼 그럴수도 있겠네요. 수정했습니다 :)

2024-03-21 05:21 UTC, klkim1913 commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +    private LocalDateTime modifiedAt;
앗

2024-03-21 05:25 UTC, klkim1913 commented
수정 및 의견 달았습니다!
확인하시고 추가 의견이나 머지 해주시면 될거같습니다 :)

2024-03-21 05:25 UTC, yeonkkk commented on src/main/java/server/user/dto/response/UserAnswersResponse.java
> +import static lombok.AccessLevel.PROTECTED;
인텔리제이에 제거하는 단축키 있슴다 ㅎㅎ 윈도우는 ctrl + alt  + o 라네요 ㅎ 
그리고 아마 사용 안하는 임포트 제거해주는 설정도 있을거에유 함 검색해보시죵

2024-03-21 05:26 UTC, yeonkkk commented on src/main/java/server/question/entity/Question.java
> +    }
좋아요 ㅎㅎ 일단 리팩토링 하신건 그대로 두고, 다음 회의 때 이야기 해봅시다

2024-03-21 05:27 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +    public static List<QuestionListResponse> fromList(List<Question> questionList) {
ㅋㅋㅋ 저도 보고 고민 많이 하셨을 것 같다고 생각했어요 ㅠ 역시 네이밍이 제일 어렵네요

2024-03-21 05:27 UTC, yeonkkk commented on src/main/java/server/question/dto/response/QuestionListResponse.java
> +    private LocalDateTime modifiedAt;
아앗!

2024-03-21 05:28 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +        this.profile = userPutRequest.getProfile();
그렇군요!! 이해했습니다 ㅎㅎ 다른 코멘트에 남긴 것 처럼 다음 회의 때 이야기 해봐요!

2024-03-21 05:28 UTC, klkim1913 commented on src/main/java/server/user/dto/response/UserAnswersResponse.java
> +import static lombok.AccessLevel.PROTECTED;
아 제거하는 단축키랑 자동 임포트 제거는 아는데 커밋할때 잡아주는거에서 말한거에요 ㅎㅎ
수정한 파일만 대상인가봅니다 아마..

2024-03-21 05:30 UTC, yeonkkk approved these changes
경륜님, 수정해주신 사항 잘 확인했습니다!
반영 잘 해주셔서 감사해요.
고생하셨습니다!

2024-03-21 05:30 UTC, merged