[#11] comment 테스트 작성
team-saviors/saview-backend pull request #23
Opened 2024-04-16 09:33 UTC by yeonkkk

## 작업 요약
- comment 테스트 작성했습니다. 

## 연관 이슈
- close #11

## 기타 논의하고 싶은 내용
- 시간 잡고 쭉 작성 못하고 틈틈이 했더니 코드가 어리바리네요.. 리뷰 받으면서 리팩토링 하겠습니다😞
- 인수 테스트는 이후에 추가하겠습니다.
- 지난 회의에서 정한 내용들은 새로 이슈 따서 반영하겠습니다(전체 테스트 작성 끝나면).

2024-04-22 08:17 UTC, klkim1913 requested changes
요즘 일이 바뻐서 확인할 시간이 없었네요.. 검토 해주시고 저도 시간나는대로 해서 올리겠습니다 👍

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/comment/entity/CommentTest.java
> +@SuppressWarnings("NonAsciiCharacters")
여기선 테스트 명을 한글로 하기에 추가하신 어노테이션인걸 바로 알 수는 있겠지만, 혹시 다른 곳에서 사용 시 안전상의 이유로 주석으로 명시해 주는 것이 좋다고 생각합니다 :)

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/comment/entity/CommentTest.java
> +                .build();
BeforeEach를 사용해서 중복 코드를 최소화 하는것도 좋아보이네요!

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/comment/entity/CommentTest.java
> +    void 댓글_내용_수정_실패(String content) {
메서드의 이름을 조금 더 명확하게 작성하여, 어떤 시나리오를 테스트 하는지 이해하기 쉽게 하는게 좋아보입니다. 예를 들어 실패의 경우 저희는 null 또는 공백이므로 `댓글_내용에_NULL_또는_공백일_경우_수정_실패` 등으로 변경하면 나중에 확실하게 알아볼 수 있을듯 합니다.

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/ServiceTest.java
> +    protected BadgeRepository badgeRepository;
테스트 코드에서도 생성자 주입을 사용할 수 있는거같은데 상속으로 이어져있어서 약간 복잡하네요 이부분은 따로 얘기해보면 좋을듯 합니다.

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/ServiceTest.java
> +    protected BadgeRepository badgeRepository;
[참고1](https://www.inflearn.com/questions/515588/%EC%83%9D%EC%84%B1%EC%9E%90-%EC%A3%BC%EC%9E%85-%EC%84%A0%ED%83%9D-%EC%8B%9C-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%EC%9D%98-%EC%9E%A5%EC%A0%90)
[참고2](https://velog.io/@nathan29849/JUnit-Test-%EA%B5%AC%EC%A1%B0)

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +    void 코멘트_생성_성공() {
어떤 경우에 코멘트 생성이 성공하는지를 명시해주면 좋아보입니다!

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        Answer answer = saveAnswer(user, question);
saveUser(), saveQuestion(user), saveAnswer(user, question) 같은 반복되는 메서드들을 BeforeEach로 이동시켜 중복을 줄일수 있을거같습니다. 다만 모든 테스트가 이 과정을 거치는게 아니라 별도의 내부 클래스로 만들던가 팩토리 메소드를 이용해야될거같은데 어떤부분이 좋을지는 얘기해보면 좋을듯 합니다.

2024-04-22 08:17 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        long invalidCommentId = -1;
코드의 매직 넘버(의미 있는 이름의 상수로 대체될 수 있는 숫자)보다는 상단에 명시적인 상수로 사용하는 것이 가독성에 좋아보입니다 :)

2024-04-22 19:06 UTC, yeonkkk reviewed
경륜님, 꼼꼼한 리뷰 감사드립니다!

남겨주신 의견에 제가 궁금한 부분을 댓글로 남겨보았어요.
질문에 대한 답변 주시면, 확인하고 수정하는 것이 더 효율적일 것 같아서 아직 수정은 안했습니다.
코멘트 주시면 확인하고 바로 코드 수정하겠습니다. 감사합니다!

ps. 요즘 많이 바쁘신가보네요ㅠ 파이팅입니다 💪

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/ServiceTest.java
> +    protected BadgeRepository badgeRepository;
경륜님 의견 감사합니다!
그런데 제가 이해하기로는 남겨주신 자료는 테스트 클래스가 아닌, 테스트할 클래스에서 생성자 주입을 했을 때의 이점 같아서요.. 혹시 제가 잘못 이해한 거라면 추가적인 설명을 부탁드려도 될까요?
이미 저희는 테스트 대상이 되는 클래스에는 생성자 주입을 사용하고 있어서, 말씀하시고자 하는 부분을 조금 더 자세히 알려주시면 감사하겠습니다!🥲

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/comment/entity/CommentTest.java
> +                .build();
예리 하십니다 👍

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/comment/entity/CommentTest.java
> +    void 댓글_내용_수정_실패(String content) {
좋은데요?! 수정하겠습니다 ㅎㅎ

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/comment/service/CommentServiceTest.java
> +    void 코멘트_생성_성공() {
어떤 식으로 작성하면 좋을지 예시를 주실 수 있을까요?
코멘트 생성이 성공하려면 많은 조건이 필요해서, 이름 명시하기가 조금 어렵게 느껴져서요!

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        long invalidCommentId = -1;
매직 넘버를 상수화 하는 것은 좋은 의견 같습니다👍
그런데 주신 의견에 궁금증이 있습니다. 
1. 상수를 사용하는 목적이 매직 넘버의 의미를 명시하기 위함이라면, 현재도 변수의 이름을 통해 그 의미를 명시하고 있는데 어떤 부분에서 상수를 사용하는게 좋을 것 같다고 생각하신건지 궁금합니다!
2. 현재 -1 값을 `invalidCommentId`와 `invalidAnswerId` 에서 모두 사용하고 있는데, 만약 상수화 한다면 같은 값을 다른 상수로 선언하는 것, 범용적인 `INVALID_ID`와 같은 상수를 선언 하는 것 중 어떤 방향을 생각하셨나요?

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        Answer answer = saveAnswer(user, question);
말씀처럼 중복 코드를 줄이는 방법은 다양하니 회의 때 이야기 한번 해보죠!

2024-04-22 19:06 UTC, yeonkkk commented on src/test/java/server/comment/entity/CommentTest.java
> +@SuppressWarnings("NonAsciiCharacters")
좋습니다! 
그런데 궁금한게 경륜님은 제가 작성한 것 처럼 1. 메서드명을 한글로 하는 것과 2. 어노테이션을 통해 메서드 명을 명시하는 것, 3. 메서드명을 영어로 잘 작성해서 의미 전달하는 것 중에 어떤 것을 선호하시나요? 단순한 궁금증입니다ㅎㅎ

2024-04-23 01:39 UTC, klkim1913 commented on src/test/java/server/comment/entity/CommentTest.java
> +@SuppressWarnings("NonAsciiCharacters")
가독성이 중요하다고 생각해서 한글로 하는 게 좋은 거 같습니다. 가끔 변수도 한글로 하면 좋겠다고 생각도 하구요.
현재로써는 테스트 목적상 따로 어노테이션으로 명시할 필요는 없어 보이긴 하네요.

2024-04-23 01:48 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +    void 코멘트_생성_성공() {
`답변에_대한_코멘트_생성_성공`과 같이 구체적인 케이스를 말한거였습니다.
다양한 상황에서 코멘트를 달 수 있는 경우 어떤 코멘트인지 파악하는 용으로 ㅎ

2024-04-23 02:02 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        long invalidCommentId = -1;
제일 우선으로 생각한 이유는 의미의 명확성입니다.
변수명으로도 의미는 알아볼 수 있지만 지역적으로 사용되기 때문에 `INVALID_ID`라는 이름의 상수로 지정하게 된다면 그 의미를 명확하게 전달할 수 있다고 생각해요. 
부가적으로는 공통된 사용이 가능하기에 타입의 안정성과 유지보수 측면에서도 좋다고 생각합니다 :)

2024-04-23 02:06 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        long invalidCommentId = -1;
제가 생각했을때는 ID는 항상 양수로 고정되어있고 향후에 변경될 가능성이 없다고 보기 때문에, 중복을 줄이고 관리를 편하게 하기 위해서는 INVALID_ID가 좋아보입니다. 그러나 이건 둘다 장단점이 있는거라 프로젝트 내용을 토대로 합의하면 될거같습니다.

2024-04-23 02:35 UTC, klkim1913 commented on src/test/java/server/ServiceTest.java
> +    protected BadgeRepository badgeRepository;
엇 첫번째 링크는 제가 잘못 보낸게 맞네요..
사실 테스트 클래스에서는 둘다 유용하게 사용할 수 있어서 괜찮은데 개인적으로 일관성을 좀 더 보기는 했습니다.
다시 보니 상속의 경우도 복잡하지는 않았네요.

`private final CommentService commentService;

    @Autowired
    public CommentServiceTest(QuestionRepository questionRepository, AnswerRepository answerRepository, UserRepository userRepository, CommentRepository commentRepository, BadgeRepository badgeRepository, CommentService commentService) {
        super(questionRepository, answerRepository, userRepository, commentRepository, badgeRepository);
        this.commentService = commentService;
    }`

2024-04-23 06:29 UTC, yeonkkk commented on src/test/java/server/ServiceTest.java
> +    protected BadgeRepository badgeRepository;
저는 현재는 통합테스트가 CommentService에 대한 테스트 밖에 없지만, 다른 테스트가 추가되면 동일한 필드를 가져서 중복 코드가 발생하기 때문에 공통된 코드를 상위 클래스로 빼서 관리하고자 했어요. 
그래서 말씀하신 것 처럼 크게 복잡한 로직은 없습니다!

2024-04-23 06:31 UTC, yeonkkk commented on src/test/java/server/comment/service/CommentServiceTest.java
> +    void 코멘트_생성_성공() {
아하! 현재는 답변에 대한 코멘트만 있어서 거기까지 생각을 못했네요. 좋은 의견 감사합니다!

2024-04-23 06:40 UTC, yeonkkk commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        long invalidCommentId = -1;
경륜님 의견처럼 `invalidcommentId` 같은 경우 하나 이상의 곳에서 사용되니까 중복을 줄이기 위해서 상수를 사용하는 건 좋은 것 같군요!
그런데 상수를 분리하는 것은 어떤가요? 고민해봤는데 ` INVALID_ID` 로 작성하면 의미가 조금 모호한 것 같아서요. 답변과 코멘트에서 현재는 유효하지 않은 id값이지만, 임의의 id의 유효하지 않은 값이 -1인게 보장되지 않는데, 네이밍만 보고 가져다 쓸 수 있으니 ` INVALID_ANSWER_ID`, ` INVALID_COMMENT_ID`로 분리하면 어떤가 싶습니다.

2024-04-23 06:41 UTC, yeonkkk commented on src/test/java/server/comment/entity/CommentTest.java
> +@SuppressWarnings("NonAsciiCharacters")
의견 감사합니다! 저도 동의하는 바입니다.
어노테이션에 한글 명시하는 스타일이시면 회의에서 조율하자고 하려했어요ㅎ 이 부분은 통했군요

2024-04-23 07:31 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        long invalidCommentId = -1;
넵 저도 완벽하게 동일한 의미가 아니면 분리하는게 디폴트라고 생각은 합니다. 그렇게 맞추죠 ㅎ

2024-04-29 08:35 UTC, klkim1913 commented on src/test/java/server/comment/entity/CommentTest.java
> +                .build();
이부분 약간 의견이 바뀌었네요. 회의때 얘기해보면 좋을거같습니다..!

2024-04-29 08:43 UTC, klkim1913 commented on src/test/java/server/comment/service/CommentServiceTest.java
> +        Answer answer = saveAnswer(user, question);
+ 저도 찾아보면서 생각한건데 이부분은 충분히 숨겨도 될거같은 부분인거같네요.
(잊어버릴까바 메모입니다)

2024-05-08 02:13 UTC, klkim1913 approved these changes

2024-05-08 06:48 UTC, yeonkkk commented
@klkim1913 경륜님! 리뷰 남겨주신 내용 반영해서 수정했습니다.
보시고 코멘트 추가로 남겨주시거나 merge 부탁드립니다:)

2024-05-09 08:28 UTC, merged