[#2] user 객체 로직 위임 및 컨트롤러 로직 제거
team-saviors/saview-backend pull request #9
Opened 2024-02-22 02:34 UTC by klkim1913

다른 레포 보니까 @AuthenticationPrincipal 커스텀 정의 해서 막 복잡하게 쓰던데 써보신적 있으면 알려주십셔..

resolved: #2

2024-02-24 16:54 UTC, yeonkkk requested changes
경륜님!
리팩토링 너무 잘 해주셨네요! 👍
같이 이야기해보고 싶은 부분이 있어서 Request changes로 남겼어요.
괜찮으시면 코멘트 남겨주세요!
고생하셨습니다!

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/controller/UserController.java
> +        User user = userService.createUser(userPostDto);
Service 레이어에서 DTO -> 엔티티 변환 수행을 잘 해주셨군요🚀
Service에서 Controller 로 Entity 를 바로 반환하는 것에 대해서는 어떻게 생각하시나요?
저는 적어주신 글을 참고했을 때, 아래와 같은 이유로 Service 에서 Controller로 DTO를 반환하는 건 어떨까 생각합니다.

- Service 레이어의 역할 중 하나는 비지니스 로직과 도메인을 캡슐화 하는 것
- Controller 까지 도메인이 노출될 경우, 도메인의 변경이 Controller에도 영향을 줄 수 있음 (계층간 결합도 증가/유지보수성 저하)
- DTO의 장점 중 하나가 필요한 데이터들만 전달할 수 있다는 것임

그리고 DTO 는 계층간의 데이터 전달 목적으로 사용하기 때문에, 적절하게 적용하는 것 같구요!
어떻게 생각하시나요?

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/controller/UserController.java
> +import org.springframework.security.core.annotation.AuthenticationPrincipal;
`@AuthenticationPrincipal` 커스텀 부분은 나중에 인증 쪽 만지면서 다시 이야기해보면 어떨까요?!
지금 하면 두번 수정할 것 같은 느낌이 들어서요ㅎㅎ

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/controller/UserController.java
> +        User user = userService.createUser(userPostDto);
만약 service 레이어에서 DTO를 바로 반환한다면(엔티티 -> DTO 변환 로직을 수행한다면), Controller에서 Mapper도 불필요하게 되겠어요!

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
>  import server.comment.entity.Comment;
변경된 부분이 아니라서 코드가 안잡히는데, 아래 부분 개행 지워주시면 좋을 것 같아요!
```java
@Column(nullable = false)

private String password;
```

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +    }
필드(컬럼)에 디폴트 값으로 지정 안하고 메서드로 만드신 이유가 궁금합니다!

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/service/UserService.java
> +import org.springframework.transaction.annotation.Transactional;
`findUserById()` 메서드 내부의 검증을 user 가 수행하면 어떨까요?
getter로 상태를 드러내기보다는 내부에서 상태와 로직을 숨기고 검증만 해주는 것이 좋을 것 같아서요!
아래 부분이요!
```java
        if (user.getUserStatus().equals(User.UserStatus.USER_QUIT)) {
            throw new BusinessLogicException(ExceptionCode.QUIT_USER);
        }
```

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
>  import server.question.entity.Question;
우리가 `@Setter` 애너테이션을.. 많이 사용했었네요😅
setter를 사용하면 메서드 이름으로 객체의 상태를 변경하는 목적이나 의도를 알 수가 없는 문제가 있죠.
그리고 setter를 열어두면, setter를 작성한 사람의 의도와 다르게 사용될 수 있어서 어디서든 값이 변경될 수 있는 위험이 있을 것 같아요. 그렇게 되면 객체는 일관성을 잃을 수 있고, 추후에 의도와 다르게 기능이 동작했을 때 문제를 빠르게 파악하기 어려울수도 있겠죠.
그래서 제 생각에는 가능하면 `@Setter` 애너테이션을 걷어내고, 기존에 setter가 사용된 곳은 의미가 확실한 이름의 메서드로 대체하는 것이 좋을 것 같은데 어떻게 생각하시나요?!

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +    }
그리고 이렇게 내부에 enum이나 클래스가 있는 경우, 순서를 어떻게 할지도 정하면 좋을 것 같네요!
메서드 - 내부 클래스(이넘) 순서 or 내부 클래스(이넘) - 메서드 순서

2024-02-24 16:54 UTC, yeonkkk commented on src/main/java/server/user/service/UserService.java
> +        // 초기에 도메인 변환 필수(규칙)
굳입니다

2024-02-26 07:50 UTC, klkim1913 commented on src/main/java/server/user/controller/UserController.java
> +        User user = userService.createUser(userPostDto);
디테일한 의견 감사합니다 :)
저도 이부분이 많이 고민되었는데, 일단 저희 프로젝트만 놓고 보자면 createUser는 아니지만
findUser, findUserById 등의 함수들을 보자면 하나가 아닌 여러 컨트롤러에서 쓰이고 있습니다.
그렇게 때문에 Service에서 DTO가 아닌 Entity로 리턴하여 공통적으로 사용할 수 있게 되어있구요.
'링크의 리뷰어 코멘트'를 참고해서 정리해보자면 진입단까지는 DTO를 들여서 쓰고, 반환시에는 저희의 경우처럼 재사용성을 위해 Entity를 반환한다고 되어있습니다. 일단 저는 실무에서 주로 쓴다는 의견과 재사용성에 중점을 두고 바꾸긴 했습니다!
정답이 없고 코드 복잡성과 도메인 보호의 Trade-off가 아닐까 생각이 됩니다.

이부분은 한번 맞춰보도록 하죠.

2024-02-26 07:51 UTC, klkim1913 commented on src/main/java/server/user/controller/UserController.java
> +import org.springframework.security.core.annotation.AuthenticationPrincipal;
넵 시큐리티쪽은 따로 하는게 좋을거같네요 ㅎ

2024-02-26 07:52 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
>  import server.comment.entity.Comment;
엇 이거 제가 한건 아니고 아마 인텔리제이가 모종의 분류를 해서 띄워주는거같네요..?

2024-02-26 07:55 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
>  import server.comment.entity.Comment;
지웠습니다!

2024-02-26 07:59 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
> +    }
> 필드(컬럼)에 디폴트 값으로 지정 안하고 메서드로 만드신 이유가 궁금합니다!

리팩토링한다고 그냥 메서드로 끝나버렸군요 ㅎㅎ..

2024-02-26 08:03 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
> +    }
> 그리고 이렇게 내부에 enum이나 클래스가 있는 경우, 순서를 어떻게 할지도 정하면 좋을 것 같네요! 메서드 - 내부 클래스(이넘) 순서 or 내부 클래스(이넘) - 메서드 순서

보통 클래스 - 메서드같기는 한데 정해봅시다!

2024-02-26 08:12 UTC, klkim1913 commented on src/main/java/server/user/service/UserService.java
> +import org.springframework.transaction.annotation.Transactional;
오 좋은 의견 감사합니다!

2024-02-26 09:15 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
>  import server.question.entity.Question;
알고있다고 생각했지만 다시 보니까 더 공부를 하게되네요 좋은부분 코멘트 감사합니다 :)
의거해서 코드 몇군데 수정해봤습니다. 한번 검토 부탁드리겠습니다!

2024-02-26 09:16 UTC, klkim1913 commented on src/main/java/server/user/service/UserService.java
> +        // 초기에 도메인 변환 필수(규칙)
일단 createUser부분의 진입 DTO로의 변환이 깔끔하지 않아보여 제거했습니다.

2024-02-26 09:21 UTC, klkim1913 commented
피드백 1차 수정 완료했습니다. Test는 코드의 많은 변화에 의해 일단 삭제하고 재작성 할 예정입니다.
PasswordSetter부분 변환이 좀 어색하긴 한데 의견 주시면 감사하겠습니다.

2024-02-29 10:56 UTC, yeonkkk commented on src/main/java/server/user/controller/UserController.java
> +        User user = userService.createUser(userPostDto);
그렇군요 ! 말씀 감사해요! 
다음 회의에서 이야기 해봐요 ㅎㅎ

2024-02-29 11:14 UTC, yeonkkk approved these changes
경륜님, 피드백 반영 잘 해주셔서 감사합니다👍
approve 하겠습니다.
리뷰하면서 같이 의논하기로 한 부분들에 대해서는 다음 회의에서 다시 이야기해보면 좋을 것 같아요 :)
코멘트 조금 남겼는데 확인해보시고 반영할만하다고 느껴지시면 반영해주세요!
고생하셨습니다.

2024-02-29 11:14 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +    }
파라미터로 UserPutDto를 받고 있네요!
각각 String으로 안 받고 Dto로 받으신 이유가 궁금합니다.
이렇게 되면 Dto 변경 사항이 User에도 영향을 줄 것 같아서요!
제가 잘못 말한 부분이 있다면 말씀 주세요 많이 부족합니다 ㅎ

2024-02-29 11:14 UTC, yeonkkk commented on src/main/java/server/user/entity/User.java
> +        userStatus = USER_QUIT;
updateStatus(UserStatus) 와 같은 방식으로 만들면 재사용성에 좋을 것 같은데, 어떤가요?
물론 지금은 회원의 상태가 2개 뿐이지만요!

2024-03-05 00:38 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
> +    }
예리한 지적 감사합니다 bb

2024-03-05 00:47 UTC, klkim1913 commented on src/main/java/server/user/entity/User.java
> +        userStatus = USER_QUIT;
깔끔하겠네요. 수정했습니다!

2024-03-05 00:52 UTC, merged